from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from io import BytesIO
from PIL import Image
import numpy as np

def numpy_to_image_bytes(img_array):
    """Convert numpy image → bytes"""
    img = Image.fromarray(img_array.astype("uint8"))
    buf = BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf

def generate_pdf(patient_id, percent, confidence, mri=None, heatmap=None):

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()

    content = []

    # ===== TITLE =====
    content.append(Paragraph("<b>Brain Tumor Clinical Report</b>", styles['Title']))
    content.append(Spacer(1, 20))

    # ===== PATIENT INFO =====
    content.append(Paragraph(f"<b>Patient ID:</b> {patient_id}", styles['Normal']))
    content.append(Spacer(1, 10))

    # ===== METRICS =====
    content.append(Paragraph(f"<b>Tumor Percentage:</b> {percent:.2f}%", styles['Normal']))
    content.append(Spacer(1, 10))

    content.append(Paragraph(f"<b>Model Confidence:</b> {confidence:.2f}%", styles['Normal']))
    content.append(Spacer(1, 20))

    # ===== RISK =====
    if percent >= 15:
        risk = "HIGH RISK"
        color = "red"
    elif percent >= 5:
        risk = "MEDIUM RISK"
        color = "orange"
    else:
        risk = "LOW RISK"
        color = "green"

    content.append(Paragraph(f"<b>Risk Level:</b> <font color='{color}'>{risk}</font>", styles['Heading2']))
    content.append(Spacer(1, 20))

    # ===== IMAGES =====
    if mri is not None:
        content.append(Paragraph("<b>MRI Scan</b>", styles['Heading3']))
        content.append(Spacer(1, 10))
        img_bytes = numpy_to_image_bytes(mri)
        content.append(RLImage(img_bytes, width=250, height=250))
        content.append(Spacer(1, 20))

    if heatmap is not None:
        content.append(Paragraph("<b>AI Heatmap</b>", styles['Heading3']))
        content.append(Spacer(1, 10))
        img_bytes = numpy_to_image_bytes(heatmap)
        content.append(RLImage(img_bytes, width=250, height=250))
        content.append(Spacer(1, 20))

    # ===== FOOTER =====
    content.append(Spacer(1, 30))
    content.append(Paragraph("Generated by AI Clinical System", styles['Normal']))

    doc.build(content)

    buffer.seek(0)
    return buffer.getvalue()